### PR TITLE
Neo UI - Massive changes

### LINKED ISSUE #20: change first  patern icons and title to reflect actual patern (mosaic)
the first pattern icon and title do not reflect the actual pattern, that one being actually mosaic pattern.
changing that so...

### LINKED ISSUE #24: Reorganize UI
The toolbar and buttons should be rearranged in order to be more intuitive.

* Menu bar:
    * File
    * Model
    * Configuration
    * Pattern
    * View
    * Help
* Toolbar:
    * Slicer
    * Template:
        * Bit options
        * Layer options
        * Pattern
        * Pattern parameters
    * Auto-optimizer
* Review:
    * Display options
    * Selected slice
    * Replace bit

Between toolbar and status bar (in the bottom), there would be a logger.

### LINKED ISSUE #57: Different pattern for different layer
2D view should allow user to choose different pattern for a specific layer.

### LINKED ISSUE #58: Cannot slice an other model
## Expected behaviour

I'm trying to do slice a new model after paving an other.

## Actual behaviour

But the Slice Tool is caught in

> java.lang.RuntimeException
	at meshIneBits.util.Shape2D.optimize(Shape2D.java:172)
	at meshIneBits.slicer.SliceTool.run(SliceTool.java:122)
	at java.lang.Thread.run(Thread.java:748)

## Steps to reproduce the error

1. 
2. 
3.

### LINKED ISSUE #63: Dynamic pavement
Define a region in which we can choose an other pattern to fill in.

### LINKED ISSUE #66: unable to save
## Expected behaviour

I'm trying to do sae blob after slcicing and populating a with classic brick pattern

I get an failed to save in status bar.

### PR DESCRIPTION
**Pull request by perfectstrong**
* Reorganize UI for more friendly environment. Close #24 
* Dynamic pavement: 
    * Pave layer: each layer can have a different pattern. Close #57 
    * Pave region: select a region to pave with an other pattern. Close #63 
    * Pave fill: fill in the left space of layer with an other pattern.
* Now you can freely rotate bit prevision while holding CTRL and scrolling mouse.
* Remove rotating selected bits for poor performance.
* Add appropriate icons for patterns. Close #20 
* Fix bugs: close #58, close #66 

neoui

Test version: [MeshIneBits-0.4.1.jar](https://mega.nz/#!jcNmEaZK!EADzfJ_u_fK-HunGY8Fw1FDuyNTO5aVpp458Vpg9Crs)

### CODE REVIEW

**Comment by ChrisdAutume** [comment]
Interface refactoring look very nice !
But I have bugs with the pavement step. I have thread exception when I'm running it. 

`
Paving mesh parallelly with Classic Brick Pattern
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at meshIneBits.Layer.getBits3dKeys(Layer.java:95)
	at meshIneBits.gui.MeshWindowCore.paintBits(MeshWindowCore.java:409)
	at meshIneBits.gui.MeshWindowCore.paintComponent(MeshWindowCore.java:301)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at meshIneBits.Layer.getBits3dKeys(Layer.java:95)
	at meshIneBits.gui.MeshWindowCore.paintBits(MeshWindowCore.java:409)
	at meshIneBits.gui.MeshWindowCore.paintComponent(MeshWindowCore.java:301)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "Thread-22" java.lang.NullPointerException
	at meshIneBits.gui.MeshController.lambda$updateAvailableArea$1(MeshController.java:238)
	at java.util.Vector.forEach(Vector.java:1275)
	at meshIneBits.gui.MeshController.updateAvailableArea(MeshController.java:237)
	at meshIneBits.gui.MeshController.calculateRealToPavement(MeshController.java:201)
	at meshIneBits.gui.MeshController.update(MeshController.java:119)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at meshIneBits.Layer.rebuild(Layer.java:64)
	at meshIneBits.Layer.startPaver(Layer.java:293)
	at meshIneBits.Mesh$PavingWorkerSlave.run(Mesh.java:568)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-34" java.lang.NullPointerException
	at meshIneBits.gui.MeshController.lambda$updateAvailableArea$1(MeshController.java:238)
	at java.util.Vector.forEach(Vector.java:1275)
	at meshIneBits.gui.MeshController.updateAvailableArea(MeshController.java:237)
	at meshIneBits.gui.MeshController.calculateRealToPavement(MeshController.java:201)
	at meshIneBits.gui.MeshController.update(MeshController.java:119)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at meshIneBits.Layer.rebuild(Layer.java:64)
	at meshIneBits.Layer.startPaver(Layer.java:293)
	at meshIneBits.Mesh$PavingWorkerSlave.run(Mesh.java:568)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-23" java.lang.NullPointerException
	at meshIneBits.gui.MeshController.lambda$updateAvailableArea$1(MeshController.java:238)
	at java.util.Vector.forEach(Vector.java:1275)
	at meshIneBits.gui.MeshController.updateAvailableArea(MeshController.java:237)
	at meshIneBits.gui.MeshController.calculateRealToPavement(MeshController.java:201)
	at meshIneBits.gui.MeshController.update(MeshController.java:119)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at meshIneBits.Layer.rebuild(Layer.java:64)
	at meshIneBits.Layer.startPaver(Layer.java:293)
	at meshIneBits.Mesh$PavingWorkerSlave.run(Mesh.java:568)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-12" java.lang.NullPointerException
	at meshIneBits.gui.MeshController.lambda$updateAvailableArea$1(MeshController.java:238)
	at java.util.Vector.forEach(Vector.java:1275)
	at meshIneBits.gui.MeshController.updateAvailableArea(MeshController.java:237)
	at meshIneBits.gui.MeshController.calculateRealToPavement(MeshController.java:201)
	at meshIneBits.gui.MeshController.update(MeshController.java:119)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at meshIneBits.Layer.rebuild(Layer.java:64)
	at meshIneBits.Layer.startPaver(Layer.java:293)
	at meshIneBits.Mesh$PavingWorkerSlave.run(Mesh.java:568)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-19" java.lang.NullPointerException
	at meshIneBits.gui.MeshController.lambda$updateAvailableArea$1(MeshController.java:238)
	at java.util.Vector.forEach(Vector.java:1275)
	at meshIneBits.gui.MeshController.updateAvailableArea(MeshController.java:237)
	at meshIneBits.gui.MeshController.calculateRealToPavement(MeshController.java:201)
	at meshIneBits.gui.MeshController.update(MeshController.java:119)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at meshIneBits.Layer.rebuild(Layer.java:64)
	at meshIneBits.Layer.startPaver(Layer.java:293)
	at meshIneBits.Mesh$PavingWorkerSlave.run(Mesh.java:568)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-24" java.lang.NullPointerException
	at meshIneBits.gui.MeshController.lambda$updateAvailableArea$1(MeshController.java:238)
	at java.util.Vector.forEach(Vector.java:1275)
	at meshIneBits.gui.MeshController.updateAvailableArea(MeshController.java:237)
	at meshIneBits.gui.MeshController.calculateRealToPavement(MeshController.java:201)
	at meshIneBits.gui.MeshController.update(MeshController.java:119)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at meshIneBits.Layer.rebuild(Layer.java:64)
	at meshIneBits.Layer.startPaver(Layer.java:293)
	at meshIneBits.Mesh$PavingWorkerSlave.run(Mesh.java:568)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-45" java.lang.NullPointerException
	at meshIneBits.gui.MeshController.lambda$updateAvailableArea$1(MeshController.java:238)
	at java.util.Vector.forEach(Vector.java:1275)
	at meshIneBits.gui.MeshController.updateAvailableArea(MeshController.java:237)
	at meshIneBits.gui.MeshController.calculateRealToPavement(MeshController.java:201)
	at meshIneBits.gui.MeshController.update(MeshController.java:119)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at meshIneBits.Layer.rebuild(Layer.java:64)
	at meshIneBits.Layer.startPaver(Layer.java:293)
	at meshIneBits.Mesh$PavingWorkerSlave.run(Mesh.java:568)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-5" java.lang.NullPointerException
	at meshIneBits.gui.MeshController.lambda$updateAvailableArea$1(MeshController.java:238)
	at java.util.Vector.forEach(Vector.java:1275)
	at meshIneBits.gui.MeshController.updateAvailableArea(MeshController.java:237)
	at meshIneBits.gui.MeshController.calculateRealToPavement(MeshController.java:201)
	at meshIneBits.gui.MeshController.update(MeshController.java:119)
	at java.util.Observable.notifyObservers(Observable.java:159)
	at java.util.Observable.notifyObservers(Observable.java:115)
	at meshIneBits.Layer.rebuild(Layer.java:64)
	at meshIneBits.Layer.startPaver(Layer.java:293)
	at meshIneBits.Mesh$PavingWorkerSlave.run(Mesh.java:568)
	at java.lang.Thread.run(Thread.java:748)
`

File: src/main/java/meshIneBits/gui/MeshWindow.java [hunk 1]
```diff
@@ -0,0 +1,713 @@
...
+        };
+        meshActionList.add(newBit);
+
+        MeshToggleAction toggleShowSlice = new MeshToggleAction(
+                "toggleShowSlice",
+                "Show/Hide Layer Border",
+                "layer-border-toggle.png",
+                "Show or hide boundary of layer",
+                "",
+                meshController::toggleShowSlice
```
Comment (ChrisdAutume) [inline src/main/java/meshIneBits/gui/MeshWindow.java]: Should be better to pass the "state" of the button than just toogle the state in the model. Issue occur during my test (button unpressed but action on)
